
%% ------------------------------------------------------------------------
% filename: buildAllDecisionAppliedPolicyMatrix.m
% rbd 10/26/19
% University of North Dakota 
% EE 999 ; Professor Tavakolian 
%% ------------------------------------------------------------------------
%policyA = [ 1 1 1 1 1 1]; % Policy A not realted to classifier A!
%AvgOnlyFlag = 1;

% Fluor Matrices
[AppliedPolicyMatrixFluorA] = buildDecisionAppliedPolicyMatrix(yFluorExpA,...
                                      SpectFluorClassifierFinalAAvgResults,...
                                      SpectFluorClassifierFinalAVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;
                                  
[AppliedPolicyMatrixFluorB] = buildDecisionAppliedPolicyMatrix(yFluorExpB,...
                                      SpectFluorClassifierFinalBAvgResults,...
                                      SpectFluorClassifierFinalBVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;

% Raman Matrices
[AppliedPolicyMatrixRamanA] = buildDecisionAppliedPolicyMatrix(yRamanExpA,...
                                      SpectRamanClassifierFinalAAvgResults,...
                                      SpectRamanClassifierFinalAVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;
                                  
[AppliedPolicyMatrixRamanB] = buildDecisionAppliedPolicyMatrix(yRamanExpB,...
                                      SpectRamanClassifierFinalBAvgResults,...
                                      SpectRamanClassifierFinalBVarResults,policyA,...
                                      AvgOnlyFlag);
                                  
% SWIR Matrices
[AppliedPolicyMatrixSWIRA] = buildDecisionAppliedPolicyMatrix(ySWIRExpA,...
                                      SpectSwirClassifierFinalAAvgResults,...
                                      SpectSwirClassifierFinalAVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;
                                  
[AppliedPolicyMatrixSWIRB] = buildDecisionAppliedPolicyMatrix(ySWIRExpB,...
                                      SpectSwirClassifierFinalBAvgResults,...
                                      SpectSwirClassifierFinalBVarResults,policyA,...
                                      AvgOnlyFlag);
                                  
% Vis Matrices
[AppliedPolicyMatrixVisA] = buildDecisionAppliedPolicyMatrix(yVisExpA,...
                                      SpectVisClassifierFinalAAvgResults,...
                                      SpectVisClassifierFinalAVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;
                                  
[AppliedPolicyMatrixVisB] = buildDecisionAppliedPolicyMatrix(yVisExpB,...
                                      SpectVisClassifierFinalBAvgResults,...
                                      SpectVisClassifierFinalBVarResults,policyA,...
                                      AvgOnlyFlag);
debug = 0;