%%---------------------------------------------------------
% filename:fishParser.m
% rbd 10/13/19
% University of North Dakota 
% EE 999 ; Professor Tavakolian
%%---------------------------------------------------------
debug = 0;
%tic
% Sort Fluorescence Count and index to fish
tbl_data = tbl_Fluorescence;
[ blueTilapiaCount, ...
           blueTilapiaArray,...
           malabarSnapperCount,...
           malabarSnapperArray,...
           redSnapperCount,...
           redSnapperArray,...
           summerFlounderCount,...
           summerFlounderArray,...
           vermillionSnapperCount,...
           vermillionSnapperArray,...
           whiteBassCount,...
           whiteBassArray] = fishClassParser(tbl_data);
 debug = 0;
 fluorblueTilapiaCount        = blueTilapiaCount;
 fluorblueTilapiaArray        = blueTilapiaArray;
 fluormalabarSnapperCount     = malabarSnapperCount;
 fluormalabarSnapperArray     = malabarSnapperArray;
 fluorredSnapperCount         = redSnapperCount;
 fluorredSnapperArray         = redSnapperArray;
 fluorsummerFlounderCount     = summerFlounderCount;
 fluorsummerFlounderArray     = summerFlounderArray;
 fluorvermillionSnapperCount  = vermillionSnapperCount; 
 fluorvermillionSnapperArray  = vermillionSnapperArray;
 fluorwhiteBassCount          = whiteBassCount;
 fluorwhiteBassArray          = whiteBassArray;
 debug = 0;
 % Sort raman Count and index to fish
tbl_data = tbl_raman;
[ blueTilapiaCount, ...
           blueTilapiaArray,...
           malabarSnapperCount,...
           malabarSnapperArray,...
           redSnapperCount,...
           redSnapperArray,...
           summerFlounderCount,...
           summerFlounderArray,...
           vermillionSnapperCount,...
           vermillionSnapperArray,...
           whiteBassCount,...
           whiteBassArray] = fishClassParser(tbl_data);
 debug = 0;
 ramanblueTilapiaCount        = blueTilapiaCount;
 ramanblueTilapiaArray        = blueTilapiaArray;
 ramanmalabarSnapperCount     = malabarSnapperCount;
 ramanmalabarSnapperArray     = malabarSnapperArray;
 ramanredSnapperCount         = redSnapperCount;
 ramanredSnapperArray         = redSnapperArray;
 ramansummerFlounderCount     = summerFlounderCount;
 ramansummerFlounderArray     = summerFlounderArray;
 ramanvermillionSnapperCount  = vermillionSnapperCount; 
 ramanvermillionSnapperArray  = vermillionSnapperArray;
 ramanwhiteBassCount          = whiteBassCount;
 ramanwhiteBassArray          = whiteBassArray;
 debug = 0;
 % Sort SWIR Count and index to fish
tbl_data = tbl_SWIR;
[ blueTilapiaCount, ...
           blueTilapiaArray,...
           malabarSnapperCount,...
           malabarSnapperArray,...
           redSnapperCount,...
           redSnapperArray,...
           summerFlounderCount,...
           summerFlounderArray,...
           vermillionSnapperCount,...
           vermillionSnapperArray,...
           whiteBassCount,...
           whiteBassArray] = fishClassParser(tbl_data);
 debug = 0;
 swirblueTilapiaCount        = blueTilapiaCount;
 swirblueTilapiaArray        = blueTilapiaArray;
 swirmalabarSnapperCount     = malabarSnapperCount;
 swirmalabarSnapperArray     = malabarSnapperArray;
 swirredSnapperCount         = redSnapperCount;
 swirredSnapperArray         = redSnapperArray;
 swirsummerFlounderCount     = summerFlounderCount;
 swirsummerFlounderArray     = summerFlounderArray;
 swirvermillionSnapperCount  = vermillionSnapperCount; 
 swirvermillionSnapperArray  = vermillionSnapperArray;
 swirwhiteBassCount          = whiteBassCount;
 swirwhiteBassArray          = whiteBassArray;
 debug = 0;
  % Sort VIS Count and index to fish
tbl_data = tbl_vis;
[ blueTilapiaCount, ...
           blueTilapiaArray,...
           malabarSnapperCount,...
           malabarSnapperArray,...
           redSnapperCount,...
           redSnapperArray,...
           summerFlounderCount,...
           summerFlounderArray,...
           vermillionSnapperCount,...
           vermillionSnapperArray,...
           whiteBassCount,...
           whiteBassArray] = fishClassParser(tbl_data);
 debug = 0;
 visblueTilapiaCount        = blueTilapiaCount;
 visblueTilapiaArray        = blueTilapiaArray;
 vismalabarSnapperCount     = malabarSnapperCount;
 vismalabarSnapperArray     = malabarSnapperArray;
 visredSnapperCount         = redSnapperCount;
 visredSnapperArray         = redSnapperArray;
 vissummerFlounderCount     = summerFlounderCount;
 vissummerFlounderArray     = summerFlounderArray;
 visvermillionSnapperCount  = vermillionSnapperCount; 
 visvermillionSnapperArray  = vermillionSnapperArray;
 viswhiteBassCount          = whiteBassCount;
 viswhiteBassArray          = whiteBassArray;
 %toc
 debug = 0;
 % Take sample measurements from fish class with min number of samples
 blueTilapiaSampleMeas       = min([fluorblueTilapiaCount,ramanblueTilapiaCount,swirblueTilapiaCount,visblueTilapiaCount]);
 malabarSnapperSampleMeas    = min([fluormalabarSnapperCount,ramanmalabarSnapperCount,swirmalabarSnapperCount,vismalabarSnapperCount]);
 redSnapperSampleMeas        = min([fluorredSnapperCount,ramanredSnapperCount,swirredSnapperCount,visredSnapperCount]);
 summerFlounderSampleMeas    = min([fluorsummerFlounderCount,ramansummerFlounderCount,swirsummerFlounderCount,vissummerFlounderCount]);
 vermillionSnapperSampleMeas = min([fluorvermillionSnapperCount,ramanvermillionSnapperCount,swirvermillionSnapperCount,visvermillionSnapperCount]);
 whiteBassSampleMeas         = min([fluorwhiteBassCount,ramanwhiteBassCount,swirwhiteBassCount,viswhiteBassCount]);
 debug = 0;
 
 
                         