%% ------------------------------------------------------------------------
% filename: learnFishSolo.m
% rbd 11/5/19
% University of North Dakota 
% EE 999 ; Professor Tavakolian 
% Description: Predict Fluor Sensor Fish

%% ------------------------------------------------------------------------
 randomRuns = 10;   % Number of random runs for a train
 M = classes;   % Types of Fish to classify
 N = TrainSize; % sample random size
 
samples_fluorescence = size(tbl_Fluorescence);
num_meas_fluorescence = samples_fluorescence(1);
dim_fluorescence = samples_fluorescence(2);

samples_raman = size(tbl_raman);
num_meas_raman = samples_raman(1);
dim_raman = samples_raman(2);

samples_swir = size(tbl_SWIR);
num_meas_swir = samples_swir(1);
dim_swir = samples_swir(2);

samples_vis = size(tbl_vis);
num_meas_vis = samples_vis(1);
dim_vis = samples_vis(2);

% Fluor Sensors
 [avgSensorAccuracyFlA,varSensorAccuracyFA,sensorAccuracyFA] = predictSpectFluorClassifierA(tbl_Fluorescence,...
                                          randomRuns,...
                                          M,N,num_meas_fluorescence,...
                                          dim_fluorescence,...
                                          trainedSpectFluorClassifierA);

 [avgSensorAccuracyFlB,varSensorAccuracyFB,sensorAccuracyFB] = predictSpectFluorClassifierB(tbl_Fluorescence,...
                                          randomRuns,...
                                          M,N,num_meas_fluorescence,...
                                          dim_fluorescence,...
                                          trainedSpectFluorClassifierB);
% Raman Sensors
[avgSensorAccuracyRA,varSensorAccuracyRA,sensorAccuracyRA] = predictSpectRamanClassifierA(tbl_raman,...
                                          randomRuns,...
                                          M,N,num_meas_raman,...
                                          dim_raman,...
                                          trainedSpectRamanClassifierA);

[avgSensorAccuracyRB,varSensorAccuracyRB,sensorAccuracyRB] = predictSpectRamanClassifierB(tbl_raman,...
                                          randomRuns,...
                                          M,N,num_meas_raman,...
                                          dim_raman,...
                                          trainedSpectRamanClassifierB);  

% SWIR Sensors
[avgSensorAccuracySA,varSensorAccuracySA,sensorAccuracySA] = predictSpectSwirClassifierA(tbl_SWIR,...
                                          randomRuns,...
                                          M,N,num_meas_swir,...
                                          dim_swir,...
                                          trainedSpectSwirClassifierA);

[avgSensorAccuracySB,varSensorAccuracySB,sensorAccuracySB] = predictSpectSwirClassifierB(tbl_SWIR,...
                                          randomRuns,...
                                          M,N,num_meas_swir,...
                                          dim_swir,...
                                          trainedSpectSwirClassifierB);
                                                                            
% Vis
[avgSensorAccuracyVA,varSensorAccuracyVA,sensorAccuracyVA] = predictSpectVisClassifierA(tbl_vis,...
                                          randomRuns,...
                                          M,N,num_meas_vis,...
                                          dim_vis,...
                                          trainedSpectVisClassifierA);

[avgSensorAccuracyVB,varSensorAccuracyVB,sensorAccuracyVB] = predictSpectVisClassifierB(tbl_vis,...
                                          randomRuns,...
                                          M,N,num_meas_vis,...
                                          dim_vis,...
                                          trainedSpectVisClassifierB);





