%% ------------------------------------------------------------------------
% filename: learnFishSolo.m
% rbd 11/5/19
% University of North Dakota 
% EE 999 ; Professor Tavakolian 
% Description: Predict Fluor Sensor Fish

%% ------------------------------------------------------------------------

% Fluor Sensors
 [avgSensorAccuracy,varSensorAccuracy] = predictSpectFluorClassifierA(tbl_Fluorescence,...
                                          randomRuns,...
                                          M,N,num_meas_fluorescence,...
                                          dim_fluorescence,...
                                          trainedSpectFluorClassifierA);

 [avgSensorAccuracy,varSensorAccuracy] = predictSpectFluorClassifierB(tbl_Fluorescence,...
                                          randomRuns,...
                                          M,N,num_meas_fluorescence,...
                                          dim_fluorescence,...
                                          trainedSpectFluorClassifierB);
% Raman Sensors
[avgSensorAccuracy,varSensorAccuracy] = predictSpectRamanClassifierA(tbl_raman,...
                                          randomRuns,...
                                          M,N,num_meas_raman,...
                                          dim_raman,...
                                          trainedSpectRamanClassifierA);

[avgSensorAccuracy,varSensorAccuracy] = predictSpectRamanClassifierB(tbl_raman,...
                                          randomRuns,...
                                          M,N,num_meas_raman,...
                                          dim_raman,...
                                          trainedSpectRamanClassifierB);  

% SWIR Sensors
[avgSensorAccuracy,varSensorAccuracy] = predictSpectSwirClassifierA(tbl_SWIR,...
                                          randomRuns,...
                                          M,N,num_meas_swir,...
                                          dim_swir,...
                                          trainedSpectSwirClassifierA);

[avgSensorAccuracy,varSensorAccuracy] = predictSpectSwirClassifierB(tbl_SWIR,...
                                          randomRuns,...
                                          M,N,num_meas_swir,...
                                          dim_swir,...
                                          trainedSpectSwirClassifierB);
                                                                            
% Vis
[avgSensorAccuracy,varSensorAccuracy] = predictSpectVisClassifierA(tbl_vis,...
                                          randomRuns,...
                                          M,N,num_meas_vis,...
                                          dim_vis,...
                                          trainedSpectVisClassifierA);

[avgSensorAccuracy,varSensorAccuracy] = predictSpectVisClassifierB(tbl_vis,...
                                          randomRuns,...
                                          M,N,num_meas_vis,...
                                          dim_vis,...
                                          trainedSpectVisClassifierB);





